### ISSUE TITLE
surface FPM and MPM identical?

### ISSUE THREAD

**Issue by ppxma7** [georgeoneill/digitAtlas#1]
Hi George,
Just perusing this and loaded up the MPM and FPM separately in MATLAB, splattered it on a brain, and I think the files are identical. I have checked on the LD_manual.mgz in surf/FPM/ and surf/MPM. Am I being an idiot (highly possible), or is this a mistake?

Initially, I was comparing it to an older version of the atlas I found on the network drive, and my FPM was radically different, as in, it wasn't 1,2,3,4, or 5, it was probabilities between 0 and 1. I've either lost the plot, lockdown permitting of course, or something's gone wrong during the upload.

Over and out,
M
![Screenshot 2020-05-11 at 20 53 50](https://user-images.githubusercontent.com/14826019/81605956-29ab7200-93ca-11ea-8cdb-3bd4c6b52615.png)
![Screenshot 2020-05-11 at 21 00 38](https://user-images.githubusercontent.com/14826019/81606167-7c852980-93ca-11ea-8912-2888dcd4950f.png)

**Comment by georgeoneill** [comment]
Hi Michael,

It turns out I have _somehow_ replaced the group level FPM with the group level MPM in my haste back in January. I'll regenerate and reupload.

**Comment by georgeoneill** [comment]
Also, subject 009 appears to have gone awol. Will recitfy that too.

**Comment by georgeoneill** [comment]
Okay I think I've fixed this. going to tentatively close this. Feel free to reopen if I haven't quite stuck the landing.
